"""add image_path to items

Revision ID: 59c7850d89cd
Revises: 4477ce3f48a7
Create Date: 2026-09-19 12:08:05.112230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c7850d89cd'
down_revision = '4477ce3f48a7'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.Text(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['customer_id'], ['id'])
        batch_op.alter_column('customer_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
